export default  [
  {id: 1, val: 'Amusement Hire'},
  {id: 2, val: 'App & Website Developers'},
  {id: 3, val: 'Audio Visual, Staging & Lighting'},
  {id: 4, val: 'Awards & Prizes'},
  {id: 5, val: 'Band, DJ, Musical Services'},
  {id: 6, val: 'Catering'},
  {id: 7, val: 'Computer Hire & IT Solutions'},
  {id: 8, val: 'Corporate Hospitality'},
  {id: 9, val: 'Entertainment & Performers'},
  {id: 10, val: 'Event Management'},
  {id: 11, val: 'Florist'},
  {id: 12, val: 'Freight & Logistics'},
  {id: 13, val: 'Gifts & Merchandise'},
  {id: 14, val: 'Personel & Support Staff'},
  {id: 15, val: 'Photography & Image Services'},
  {id: 16, val: 'Printing Services'},
  {id: 17, val: 'Registration & Identity Management'},
  {id: 18, val: 'Security Services'},
  {id: 19, val: 'Stand/Display Builders & Signage'},
  {id: 20, val: 'Team Building'},
  {id: 21, val: 'Theming, Decorations & Props'},
  {id: 22, val: 'Transportation & Hire Car'},
  {id: 23, val: 'Travel Agent'},
  {id: 24, val: 'Videography & Video Editing'},
  {id: 25, val: 'Venue'},
  {id: 26, val: 'Web Streaming'},
  {id: 27, val: 'Automobiles and Components'},
  {id: 28, val: 'Banks'},
  {id: 29, val: 'Capital Goods'},
  {id: 30, val: 'Commercial and Professional Services'},
  {id: 31, val: 'Communication Services'},
  {id: 32, val: 'Consumer Durables and Apparel'},
  {id: 33, val: 'Consumer Services'},
  {id: 34, val: 'Diversified Financials'},
  {id: 35, val: 'Energy'},
  {id: 36, val: 'Food, Beverage and Tobacco'},
  {id: 37, val: 'Food and Staples Retailing'},
  {id: 38, val: 'Health Care Equipment and Services'},
  {id: 39, val: 'Household and Personal Products'},
  {id: 40, val: 'Insurance'},
  {id: 41, val: 'Materials'},
  {id: 42, val: 'Media'},
  {id: 43, val: 'Pharmaceuticals, Biotech and Life Sciences'},
  {id: 44, val: 'Real Estate'},
  {id: 45, val: 'Retailing'},
  {id: 46, val: 'Semiconductors and Semiconductor Equipment'},
  {id: 47, val: 'Software and Services'},
  {id: 48, val: 'Technology Hardware and Equipment'},
  {id: 49, val: 'Transportation'},
  {id: 50, val: 'Utilities'},
  {id: 51, val: 'Other'},
];
