export enum EventFileTypes {
  CLIENT_EVENT_MANAGER_SHARED_FILES = 'CEMSF',
  CLIENT_INTERNAL_FILES = 'CIF',
  EVENT_FILES = 'EF',
  EVENT_MANAGEMENT_INTERNAL_FILES = 'EMIF',
  FILES_FOR_ALL_VENUES = 'FFAV',
  FILES_FOR_ALL_SUPPLIERS = 'FFAS',
  FILES_FOR_ALL_EXHIBITORS = 'FFAE',
  VENUE_FLOOR_PLAN = 'FLOOR_PLAN',
  VENUE_SHARED_FILES = 'VSF',
  VENUE_INTERNAL_FILES = 'VIF',
  SUPPLIER_SHARED_FILES = 'SSF',
  SUPPLIER_INTERNAL_FILES = 'SIF',
  EXHIBITOR_SHARED_FILES = 'EBSF',
  EXHIBITOR_INTERNAL_FILES = 'EBIF'
}
